name: hanzozt
version: 0.22.5
base: core18
summary: Netfoundry zt application suite
description: |
  The zt-tunneler provides access to the NetFoundry network 
grade: devel
confinement: strict

parts:
  zt:
    source: .
    plugin: go
    go-importpath: bitbucket.org/netfoundry/zt
    go-channel: 1.17/stable
    build-packages:
      - gcc

  random-scripts:
    source: etc/ubuntu-snap
    plugin: dump

apps:
  zt:
    command: bin/zt
    plugs:
      - home
      - network
  zt-tunnel:
    daemon: simple
    command: bin/zt-tunnel run $SNAP_COMMON/zt.json
    plugs:
      - home
      - network
      - network-control

#hooks:
#  configure:
#    plugs: [network]
